services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:${PROJECT_PATH:-/app}
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: ${PROJECT_PATH:-/app}
    command: sh -c "service redis-server start && tail -f /dev/null"
    environment:
      - DEV=1
      - IRGSH_CONFIG_PATH=${PROJECT_PATH:-/app}/utils/config.docker.yml
    privileged: true
    ports:g
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"

# Don't forget to run vm.overcommit_memory = 1, in host machine
# Temporary fix
